### ISSUE TITLE
Input mounting error

### ISSUE THREAD

**Issue by shenphen** [Lesha-spr/react-validation#122]
```Uncaught RangeError: Maximum call stack size exceeded``` this error occurs when default Input component  from 'react-validation/build/input.js' is mounted

**Comment by Lesha-spr** [comment]
Could you please share usage? Also, please make sure you're not trying to decorate original ```Input``` component from the lib since it's already decorated.

**Comment by shenphen** [comment]
```
import React from 'react';

import Input from 'react-validation/build/input';
import { email } from './validationRules';

const Example = (props) => {
    return (
        <div>
            <Input name="email" id="email" type="email" validations={[email]} value='email' />
        </div>
    )
}

export default Example;
```
In validationRules.js
```
import React from 'react';
import validator from 'validator';

export const email = (email) => {
    if(!validator.isEmail(email)) {
        return <span className='form-error is-visible'>Invalid email adress</span>
    }
}
```

Each time other stack is shown

![image](https://user-images.githubusercontent.com/23192421/31387061-536f2de6-adc9-11e7-822c-25b9d90989e0.png)

**Comment by Lesha-spr** [comment]
Fixed. Please update to 3.0.3.

**Comment by bbruneau** [comment]
This is happening to me as well. No custom components. Same error message, v3.0.7.

**Comment by bbruneau** [comment]
It seems as though this problem doesn't occur if the Input is a direct child of the Form. If it's rendered by an intermediary component, we get the Max call stack error.

**Comment by bbruneau** [comment]
I did some poking around, and it seems as though this line is to blame.

https://github.com/Lesha-spr/react-validation/blob/master/src/components/base/index.js#L35

On update, the child receives props, and then updates the context, leading to an endless loop.

**Comment by Lesha-spr** [comment]
The package is publishing from v3 branch. I really can't reproduce it. Could you please ensure you're using 3.0.7?

**Comment by 617dev** [comment]
@Lesha-spr i can confirm what @bbruneau is saying. I went to update to the latest version in a project at work because i saw you extracted the proptypes package, which would make it compatible with React 16. But now i'm getting this max call stack error too. Because like @bbruneau said some of the inputs in the form are rendered by intermediary components. So i think he's on to something. I did confirm i'm on version 3.0.7.

**Comment by 617dev** [comment]
out of curiosity i updated  react to 16 and though this problem still exists though the error is a bit more descriptive now: 
```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

If i comment out all the form fields that are rendered by intermediary components the form and validation do work without errors. One of the three i commented out, I believe is decorating the Input component from your lib, the other 2 are just to keep things organized (but even if i only take out the decorated one, i still get the max stack error). How would you recommend working around decorating a validated Input? since you said not to do that... 

BTW This all worked fine with version `2.10.9` which is what we were on before, but like i said that was preventing us from updating react to the latest because of proptypes.

**Comment by sergeysolovev** [comment]
@Lesha-spr 

Why this one was closed? The issue still persists. As it was said before
>It seems as though this problem doesn't occur if the Input is a direct child of the Form.

So if move out parts of the form to separate components (which is very React.js way of doing things), I get "Maximum update depth exceeded".

Are there any walk-arounds or plans to fix this one?
