### ISSUE TITLE
can u hidden error dom when valid?

### ISSUE THREAD

**Issue by abnerlinan** [Lesha-spr/react-validation#15]
Validation.Input runs before Validation.extendErrors(), so defaultHintClassName: 'ui-hint',
    defaultContainerClassName: ''  cannot extend by Validation.extendErrors()

**Comment by abnerlinan** [comment]
sorry for my poor english

**Comment by Lesha-spr** [comment]
Hi @abnerlinan ,

I've refactored module due to your issue [see commit](https://github.com/Lesha-spr/react-validation/commit/e98b81a2f0b9288ff10aa19693789fbb319aa7f3) Could you please check [demo](http://lesha-spr.github.io/react-validation/) (extend-validation.js) file? I've added extending example.

Please close issue if everything fine.

Thanks,
Oleksii

**Comment by abnerlinan** [comment]
thx.

**Comment by abnerlinan** [comment]
another question:
can u hidden error dom when valid?
-----

`<span class="error" data-reactid=".0.0.0.$/=10.$/=10.$/=11.$/=10.1"></span>`
I have some style in error.span, when input valid, error text change to null,  but style still alive

**Comment by abnerlinan** [comment]
my code 
`if(this.state.errorMessage != null){
            errorDom = React.createElement("span", {className: errors.defaultHintClassName}, this.state.errorMessage);
        }
        return React.createElement("div", {className: this.props.containerClassName || errors.defaultContainerClassName}, 
            input, 
            errorDom
        );`

**Comment by Lesha-spr** [comment]
Hi @abnerlinan 

Please check 1.5.1 version. This should fix this issue.
Also please close issue if everything is fine.

Thanks,
Oleksii
