### ISSUE TITLE
Could there be any support for defaultValue?

### ISSUE THREAD

**Issue by Cyval** [Lesha-spr/react-validation#30]
Hi, this may be unusual for react components, but I would like to ask if there could any support for defaultValue for react-validation? Like

`if(this.props.defaultValue) `
  `  return the input`
`else`
  `  return the input with onchange`

Is this one possible?

I asked because I am using this amazing library together with Google Maps API , and I am encountering some errors when a defaultValue is not supplied to the input. I end up using the standard `input` element. Thanks in advance

**Comment by Lesha-spr** [comment]
Hi @Cyval ,

This is your call to use controlled or uncontrolled inputs. If you need validation on it - use controlled input. Since Google APIs has rich functionality I assume you don't need to validate it by some other third party API. There is absolutely nothing wrong with mixing Validation controls and native DOM controls.

Is that answering your question?

Thanks,
Oleksii
