### ISSUE TITLE
How to get the context errors array from the validation button?

### ISSUE THREAD

**Issue by DidiWillems** [Lesha-spr/react-validation#62]
I'd like to use the errors array for showing all errors in the form. But how do I get to it? I tried Validation.components.Button.contextTypes.errors but that returns the function. Can I make this return the errors outside the validation button?

**Comment by Lesha-spr** [comment]
Hi @DidiWillems ,

Yes, this is a good point. It's not possible at the moment - I left **TBD** on current behavior.
This is definitely a feature for the future release. If you have a time, could you please prepare the PR to provide such feature?

Thanks,
Oleksii

**Comment by snakeyak** [comment]
+1 for bringing `validateAll()` back, I'm still stuck using an old forked version where this was available

**Comment by Lesha-spr** [comment]
Hey @snakeyak,

```validateAll``` have been returned. It's just doesn't return errors map at the moment. Did you see it?

**Comment by snakeyak** [comment]
@Lesha-spr Yes, I'm using this method in the older version (pre-2.10). But as of right now it just returns undefined for both valid and invalid forms, correct? That means it has no use currently..

**Comment by Cyval** [comment]
If I understand it correctly, I do this for getting the errors:

`<Form ref='form'>`

Then I do:

`this.refs.form.state.errors`

**Comment by Lesha-spr** [comment]
At the moment `errors` map represents name(of original component)-hint(to show error)

**Comment by Lesha-spr** [comment]
@snakeyak , @DidiWillems ,

Guys, I'm already working to `validateAll` return errors model. API might be a bit reworked to:
`validateAll(callback)` - `{Function} callback` will accept errors model.

**Comment by DidiWillems** [comment]
@Lesha-spr , @Cyval .  Oke cool. I´m trying to make it from the ref form for now.

**Comment by DidiWillems** [comment]
I solved it for now by getting the array on an input change:
`    onChange(event) {
        this.setState({
            errorsArray: Object.keys(this.refs.form.state.errors);
        });
    }`

**Comment by Lesha-spr** [comment]
@snakeyak , @DidiWillems ,

Just to clarify: would the whole errors array be helpful for each component OR we need just the first occured error?

For example `{componentName: 'required'}` or `{componentName: ['required', 'alpha']}`

Thanks,
Oleksii

**Comment by snakeyak** [comment]
@Lesha-spr For my current usage what I need from the validateAll method is : 
1)Validate all fields in the form (even the ones that were not triggered/modified yet) and trigger (show the hints) invalid ones
2)Return whether the form as a whole is valid or not

I use this to move the user onto the next form with a button (that also does some further checks outside of the form), provided that the previous form is valid (so the validatateAll also has to happen synchronously). This was the behaviour of this method before the updates and worked great, I just checked the return object whether it is empty (form valid) or not (form invalid).

Although I personally only need true or false, I'm guessing the whole error array is more "future-proof" and will enable more use cases, just my 2 cents..

This is the forked version I'm still using because of it: https://github.com/snakeyak/react-validation

**Comment by Lesha-spr** [comment]
Returned `validateAll` to return errors map. Please checkout 2.10.7 and close the issue if everything is fine.

Thanks,
Oleksii

**Comment by snakeyak** [comment]
Works perfectly now. Thanks a lot!

**Comment by DidiWillems** [comment]
Just one more question. I can´t figure out how o use the validateAll(). Where and how can I use it? Can you give me an example?

**Comment by Lesha-spr** [comment]
@DidiWillems ,

There is an example on [demo](http://lesha-spr.github.io/react-validation/). So basically you just call it on your `form` ref whenever you need to validate all the controls.
